In [92]:
import numpy as np
import matplotlib.pyplot as plt
import math

images = []

for i in range(2400):
    img = plt.imread("Train/" + str((i+1)) + ".jpg")
    pixels = []
    for j in range(28):
        for k in range(28):
            pixels.append(img[j,k])
    
    pixels.append(1)
    images.append(pixels)
    
images = np.asarray(images)
print(images.shape)

(2400, 785)


In [93]:
imagesT = np.transpose(images)
print(imagesT.shape)

(785, 2400)


In [94]:
test_images = []

for i in range(200):
    img = plt.imread("Test/" + str((i+1)) + ".jpg")
    pixels = []
    for j in range(28):
        for k in range(28):
            pixels.append(img[j,k])
    
    pixels.append(1)
    test_images.append(pixels)
    
test_images = np.asarray(test_images)
print(test_images.shape)

(200, 785)


In [95]:
test_imagesT = np.transpose(test_images)
print(test_imagesT.shape)

(785, 200)


In [96]:
labels = np.genfromtxt('Test/Test Labels.txt')
print(labels)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 8. 8. 8. 8. 8. 8. 8. 8.
 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9.
 9. 9. 9. 9. 9. 9. 9. 9.]


In [97]:
t = np.ones((2400,10))
t = np.negative(t)
for i in range(10):
    t[(i*240):((i+1)*240),i:(i+1)] = 1
    
print(t.shape)

(2400, 10)


In [106]:
#images = np.true_divide(images, 255)
#test_images = np.true_divide(test_images, 255)
print(images)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.53787005e-05]]


In [107]:
#Adding mean values for each class with respect to each pixel in the training data
means_matrix = np.zeros((784, 10))
for k in range(10):  
    for i in range(784):
        for j in range(240):
            means_matrix[i][k] += images[j*(k+1)][i]
        means_matrix[i][k] = means_matrix[i][k] / 240
print(means_matrix)

[[5.12623350e-07 1.28155837e-07 3.97283096e-06 ... 4.29322056e-06
  2.94758426e-06 3.33205177e-06]
 [2.75535051e-06 1.15340254e-06 5.12623350e-06 ... 5.31846726e-06
  4.16506472e-06 3.97283096e-06]
 [2.24272716e-06 1.28155837e-06 3.26797386e-06 ... 5.19031142e-06
  3.52428553e-06 4.54953223e-06]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [103]:
variance_matrix = np.zeros((784, 10))
for k in range(10):
    for i in range(784):
        for j in range(240):
            variance_matrix[i][k] += (images[j*(k+1)][i] - means_matrix[i][k])**2
        variance_matrix[i][k] = variance_matrix[i][k] / 240
        if(variance_matrix[i][k] < 0.01):
            variance_matrix[i][k] = 0.01
print(variance_matrix)

[[0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 ...
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]
 [0.01 0.01 0.01 ... 0.01 0.01 0.01]]


In [104]:
def calculate_guassian(x,mean,variance):
    guassian_value = (1 / np.sqrt(2 * np.pi * variance)) * math.exp((-1) * ((x-mean)**2 / (2 * variance)))
    return guassian_value

In [102]:
probabilities_matrix = np.ones((200, 10))
for k in range(10):    
    for i in range(200):
        for j in range(784):
            probabilities_matrix[i][k] = probabilities_matrix[i][k] * calculate_guassian(test_images[i][j],means_matrix[j][k],variance_matrix[j][k])
        

c:\users\ibram medhat\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in double_scalars
  
c:\users\ibram medhat\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in double_scalars
  
c:\users\ibram medhat\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in double_scalars
  """
c:\users\ibram medhat\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in double_scalars
  """
